//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workflow {
	
	
	public partial class Admin {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox Email;
		
		protected System.Web.UI.WebControls.TextBox Password;
		
		protected System.Web.UI.WebControls.TextBox PasswordRepeat;
		
		protected System.Web.UI.WebControls.Button RegisterBtn;
	}
}
