//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workflow {
	
	
	public partial class Projects {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label userLbl;
		
		protected System.Web.UI.WebControls.Button AdminBtn;
		
		protected System.Web.UI.WebControls.Button logout;
		
		protected System.Web.UI.WebControls.Button dashboard;
		
		protected System.Web.UI.WebControls.Button workflow;
		
		protected System.Web.UI.WebControls.Button current;
		
		protected System.Web.UI.WebControls.Button form;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl projectListing;
		
		protected System.Web.UI.WebControls.Button CreateNewProjectBtn;
		
		protected System.Web.UI.WebControls.Label ProjectError;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl numberShowing;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl projectList;
		
		protected System.Web.UI.WebControls.Button Button2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl projectBuilder;
		
		protected System.Web.UI.WebControls.Panel ProjectNamePanel;
		
		protected System.Web.UI.WebControls.TextBox ProjectName;
		
		protected System.Web.UI.WebControls.DropDownList CompanySelect;
		
		protected System.Web.UI.WebControls.DropDownList WorkflowSelect;
		
		protected System.Web.UI.WebControls.DropDownList CoachSelect;
		
		protected System.Web.UI.WebControls.TextBox ProjectNotes;
		
		protected System.Web.UI.WebControls.Button CreateProjectBtn;
		
		protected System.Web.UI.WebControls.HiddenField SelectedCompany;
		
		protected System.Web.UI.WebControls.HiddenField SelectedWorkflow;
		
		protected System.Web.UI.WebControls.HiddenField SelectedCoach;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl projectViewer;
		
		protected System.Web.UI.WebControls.Button ProjectFileDownloader;
	}
}
