//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workflow {
	
	
	public partial class Workflows {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label userLbl;
		
		protected System.Web.UI.WebControls.Button AdminBtn;
		
		protected System.Web.UI.WebControls.Button logout;
		
		protected System.Web.UI.WebControls.Button dashboard;
		
		protected System.Web.UI.WebControls.Button current;
		
		protected System.Web.UI.WebControls.Button project;
		
		protected System.Web.UI.WebControls.Button form;
		
		protected System.Web.UI.WebControls.Label WorkflowError;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl workflowListing;
		
		protected System.Web.UI.WebControls.Button CreateNewWorkflowBtn;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl numberShowing;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl workflowList;
		
		protected System.Web.UI.WebControls.Button Button2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl workflowBuilder;
		
		protected System.Web.UI.WebControls.TextBox WorkflowName;
		
		protected System.Web.UI.WebControls.PlaceHolder WorkflowSteps;
		
		protected System.Web.UI.WebControls.Button AddWorkflowComponentBtn;
		
		protected System.Web.UI.WebControls.Button CreateWorkflowBtn;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl workflowViewer;
	}
}
